#Host vars
server_hostname: "linux-server01"
virtual_domain: "alma.com www.alma.com"
virtual_host_ip: "10.0.0.1"

#PHP Settings
php_modules: [ 'php', 'php-mysqli', 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]
php_version: "8.0"
 
#MySQL Settings
mysql_root_username: "root"
mysql_root_password: "ESr8S?U_55},VF<$"
mysql_db: "almadb"
mysql_user: "almauser"
mysql_password: "&w:.:sf2R%%hFhVa"
 
#HTTP Settings
http_host: "alma.com"
http_conf: "alma.com.conf"
http_port: "80"

#Epel repo
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"
epel_repo_disable: false

#Remi repo
remi_repo_url: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
remi_repo_gpg_key_url: "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
