# Install and set up MySQL server for alma.com
---
- name: Install MySQL packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mysql-server
      - php-mysqlnd
      - python3-PyMySQL
  
- name: Enable the MySQL service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Set MySQL root Password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{ mysql_root_password }}'
    state: present

- name: Create `/root/.my.cnf` with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  become: yes
  notify: restart mysqld

- name: Create database for alma.com
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true
 
- name: Create MySQL user for alma.com
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true

#For security: Remove the anonymous user and ensure default user is present in MySQL
- name: Disable root remote login and remove anonymous User.
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User!='{{ mysql_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false
